sudo:required
language: generic 
services:
   - docker 


before_install:
   - docker build -t vishalc35/dockerexampleworkflow -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-406598666440"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"



