sudo: required
services:
  - docker 

before_install:
  - docker build -t vishalc35/dockerexampleworkflow -f Dockerfile.dev .

script:
  - docker run vishalc35/dockerexampleworkflow npm run test -- --coverage
